Add screenshot to testresult for XML report
FlaUI/FlaUI pull request #535
Opened 2022-11-29 14:59 UTC by igorrecioh

[L143-L145] I have added the AddTestAttachment method in order to include taken screenshot to the report and, therefore, the screenshot will be available in XML report, generated at the end of execution. This is interesting when parsing XML to generate, for example, an HTML report.

[L278-L286] I have extracted from TakeScreenShot the generation of the full path so that I can use it in previously explained code.

2023-10-05 12:04 UTC, igorrecioh commented
Could anyone provide some input on this? If it is not desire, please comment and I will close PR

2023-10-25 12:14 UTC, igorrecioh commented
Hi @tomersalem @Roemer , could you please review this? If it is not a desired feature, let me know and I will close it. Thanks a lot

2023-10-25 16:21 UTC, tomersalem approved these changes

2023-10-25 16:23 UTC, igorrecioh commented
Thanks a lot, @tomersalem ! I have just updated the branch with master. I may need another review for this again, sorry.

2023-10-29 06:19 UTC, tomersalem requested changes
I like to keep previous results run, please consider adding:
`
/// <summary>
/// static member which holds the current execution date and time
/// </summary>
        private static string _testDateTime = DateTime.Now.ToString("yyyyMMddHHmmss");`

and modify:
`
protected virtual string TestsMediaPath => $@"c:\temp\testsmedia\{TestContext.CurrentContext.Test.Name}\{_testDateTime}";
`

2023-10-29 14:35 UTC, tomerbyair approved these changes

2023-10-29 14:40 UTC, tomersalem approved these changes

2023-10-29 15:10 UTC, tomersalem approved these changes
Thanks,
Tomer

2023-10-29 15:11 UTC, igorrecioh commented
@tomersalem It is failing some UI Test, need to check why. I hope this afternoon could be solved

2023-10-29 18:15 UTC, igorrecioh commented
@tomersalem It was failing due to ```{TestContext.CurrentContext.Test.Name}````as it contained some illegal characters. Now it's being sanitize to avoid that

2023-10-30 05:32 UTC, tomersalem approved these changes
👍

2023-10-30 07:28 UTC, Roemer commented on src/FlaUI.TestUtilities/FlaUITestBase.cs
> +        protected virtual string TestsMediaPath => $@"c:\temp\testsmedia\{SanitizeFileName(TestContext.CurrentContext.Test.Name)}\{_testDateTime}";
This is kind of a breaking change but I guess most people anyway overwrite this path so we should be fine.

2023-10-30 07:28 UTC, Roemer approved these changes

2023-10-30 07:28 UTC, Roemer commented
Thank you for your contribution. The change has been merged.

2023-10-30 07:28 UTC, merged